# Generated by Django 5.0.6 on 2024-05-18 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='Место')),
                ('start_time', models.TimeField(verbose_name='Время')),
                ('action', models.CharField(max_length=100, verbose_name='Действие')),
                ('useful', models.BooleanField(verbose_name='Признак полезной привычки')),
                ('reward', models.CharField(max_length=100, verbose_name='Вознагрождение')),
                ('running_time', models.FloatField(verbose_name='Время выполнения')),
                ('publicated', models.BooleanField(default=False, verbose_name='Признак публикации')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='Связная полезная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ['user'],
            },
        ),
    ]
