# Generated by Django 5.0.6 on 2024-05-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_rename_useful_habit_usefulls_alter_habit_reward'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='usefulls',
            new_name='usefull',
        ),
    ]
