# Generated by Django 5.0.6 on 2024-05-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_alter_habit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее обновление'),
        ),
        migrations.AddField(
            model_name='habit',
            name='period',
            field=models.IntegerField(default=1, verbose_name='Интервал'),
        ),
    ]
