# Generated by Django 5.0.6 on 2024-05-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_habit_last_update_habit_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_run',
            field=models.DateField(blank=True, null=True, verbose_name='Последний запуск'),
        ),
    ]
